name: 'Publish package'

on:
  workflow_call:
    inputs:
      registry-url:
        required: true
        type: string
    secrets:
      NODE_AUTH_TOKEN:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: ${{ inputs.registry-url }}
      - run: npm ci

      # pre-releases, triggered by `next` as part of git tag
      - run: npm publish --tag next
        if: ${{ contains(github.ref, 'next') }}

      # production releases
      - run: npm publish
        if: ${{ !contains(github.ref, 'next') }}
