name: 'Release a new version'

on:
  release:
    types: [published]

jobs:
  build-docs:
    uses: deltaDAO/nautilus/.github/workflows/typedoc-docusaurus.yml@main
    with:
      version: ${{ github.event.release.tag_name }}
  release-to-npmjs:
    uses: deltaDAO/nautilus/.github/workflows/publish-pkg.yml@main
    with:
      registry-url: https://registry.npmjs.org/
      access: public
    secrets:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  # release-to-github:
  #   uses: deltaDAO/nautilus/.github/workflows/publish-pkg.yml@main
  #   with:
  #     registry-url: https://npm.pkg.github.com/
  #   secrets:
  #     NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
